config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get     'login',   to: 'users/sessions#new'
    post    'login',   to: 'users/sessions#create'
    delete  'logout',   to: 'users/sessions#destroy'
    get     'signup',  to: 'users/registrations#new'
  end

  resources :users, only: :show

  resources :brands, only: [:index, :show] do
    member do
      post "add", to: "clips#create"
    end
    resources :brewages, only: [:show, :new, :create, :destroy]
    resources :feelings, except: [:index, :show]
  end
  
  resources :clips, only: [:destroy]
  
  resources :top, only: [:index] do
    collection do
      get 'search'
    end
  end

  root 'top#search'
end

app/models/feeling.rb
class Feeling < ApplicationRecord
  belongs_to :user
  belongs_to :brand

  validates :comment, length: { maximum: 140 }

  with_options presence: true do
    validates :flavor
    validates :aroma
    validates :body
    validates :sharp
    validates :favorite
  end
end

app/controllers/feelings_controller.rb
class FeelingsController < ApplicationController

  def new
    redirect_to login_url unless user_signed_in?
    @brand = Brand.find(params[:brand_id])
    @feeling = Feeling.new
  end

  def create
    @brand = Brand.find(params[:brand_id])
    @feeling = Feeling.create(feeling_params)
    redirect_to brand_path(@brand)
  end
  
  def destroy
    @brand = Brand.find(params[:brand_id])
    feeling = Feeling.find_by(brand_id: @brand.id, user_id: current_user.id)
    feeling.destroy
    redirect_to brand_path(@brand)
  end

  def edit
    @brand = Brand.find(params[:brand_id])
    @feeling = Feeling.find_by(brand_id: @brand.id, user_id: current_user.id)
  end

  def update
    feeling = Feeling.find(params[:id])
    feeling.update(feeling_params) if feeling.user_id == current_user.id
    @brand = Brand.find(params[:brand_id])
    redirect_to brand_path(@brand)
  end

  # def show
  #   @brand = Brand.find(params[:id])
  #   @feelings = @brand.feelings.includes(:user)
  # end

  def feeling_params
    params.require(:feeling).permit(:id, :comment, :flavor, :aroma, :body, :sharp, :favorite).merge(brand_id: params[:brand_id], user_id: current_user.id)
  end
end

app/helpers/feelings_helper.rb
module FeelingsHelper
end

app/views/feelings/_form.html.haml
.feelings-form.feilds
  = form_for [@brand, @feeling] do |f|
    .feelings-form__radio
      .form-title 味わい
      .feelings-form__radio__selector
        .r
          = f.radio_button :flavor, 1
          = f.label :flavor, "辛口", {value: 1}
        .r
          = f.radio_button :flavor, 2
          = f.label :flavor, "・", {value: 2}
        .r
          = f.radio_button :flavor, 3, {checked: "checked"}
          = f.label :flavor, "・", {value: 3}
        .r
          = f.radio_button :flavor, 4
          = f.label :flavor, "・", {value: 4}
        .r
          = f.radio_button :flavor, 5
          = f.label :flavor, "甘口", {value: 5}
      .form-title 香り
      .feelings-form__radio__selector
        .r
          = f.radio_button :aroma, 1
          = f.label :aroma, "穏やか", {value: 1}
        .r
          = f.radio_button :aroma, 2
          = f.label :aroma, "・", {value: 2}
        .r
          = f.radio_button :aroma, 3, {checked: "checked"}
          = f.label :aroma, "・", {value: 3}
        .r
          = f.radio_button :aroma, 4
          = f.label :aroma, "・", {value: 4}
        .r
          = f.radio_button :aroma, 5
          = f.label :aroma, "華やか", {value: 5}
      .form-title コク
      .feelings-form__radio__selector
        .r
          = f.radio_button :body, 1
          = f.label :body, "あっさり", {value: 1}
        .r
          = f.radio_button :body, 2
          = f.label :body, "・", {value: 2}
        .r
          = f.radio_button :body, 3, {checked: "checked"}
          = f.label :body, "・", {value: 3}
        .r
          = f.radio_button :body, 4
          = f.label :body, "・", {value: 4}
        .r
          = f.radio_button :body, 5
          = f.label :body, "重厚", {value: 5}
      .form-title キレ
      .feelings-form__radio__selector
        .r
          = f.radio_button :sharp, 1
          = f.label :sharp, "ふくよか", {value: 1}
        .r
          = f.radio_button :sharp, 2
          = f.label :sharp, "・", {value: 2}
        .r
          = f.radio_button :sharp, 3, {checked: "checked"}
          = f.label :sharp, "・", {value: 3}
        .r
          = f.radio_button :sharp, 4
          = f.label :sharp, "・", {value: 4}
        .r
          = f.radio_button :sharp, 5
          = f.label :sharp, "シャープ", {value: 5}
    .feelings-form__comment
      = f.label :comment, "コメント", class: "form-title"
      = f.text_area :comment
    .feelings-form__radio
      .form-title お気に入り度
      .feelings-form__radio__selector
        .r
          = f.radio_button :favorite, 1
          = f.label :favorite, "＜ 低", {value: 1}
        .r
          = f.radio_button :favorite, 2
          = f.label :favorite, "・", {value: 2}
        .r
          = f.radio_button :favorite, 3, {checked: "checked"}
          = f.label :favorite, "Like!", {value: 3}
        .r
          = f.radio_button :favorite, 4
          = f.label :favorite, "・", {value: 4}
        .r
          = f.radio_button :favorite, 5
          = f.label :favorite, "高 ＞", {value: 5}
    .feelings-form__submit
      = f.submit 'この内容できろくする', class: "submit-btn"

app/views/feelings/edit.html.haml
= render "shared/header"
- breadcrumb :feelings_edit
= render partial: 'shared/breadcrumbs'
.container
  .feelings-new.single-column
    .feelings-new__title
      %h2 #{@brand.name}のきろく
    .feelings-new__form.single-column__form
      = render "form"

      .actions
        .actions__another-links-right
          = link_to brand_feeling_path(@brand), method: :delete, class: "delete-btn" do
            %i.fas.fa-trash-alt
            きろくを削除する
        .actions__another-links
          = link_to :back, class: "back-btn" do
            %i.fas.fa-chevron-circle-right
            戻る

= render 'shared/footer'

app/views/feelings/new.html.haml
= render "shared/header"
- breadcrumb :feelings_new
= render partial: 'shared/breadcrumbs'
.container
  .feelings-new.single-column
    .feelings-new__title
      %h2 #{@brand.name}のきろく
    .feelings-new__form.single-column__form
      = render "form"
      .actions
        .actions__another-links
          = link_to :back, class: "back-btn" do
            %i.fas.fa-chevron-circle-right
            戻る

= render 'shared/footer'