config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get     'login',   to: 'users/sessions#new'
    post    'login',   to: 'users/sessions#create'
    delete  'logout',   to: 'users/sessions#destroy'
    get     'signup',  to: 'users/registrations#new'
  end

  resources :users, only: :show

  resources :brands, only: [:index, :show] do
    member do
      post "add", to: "clips#create"
    end
    resources :brewages, only: [:show, :new, :create, :destroy]
    resources :feelings, except: [:index, :show]
  end
  
  resources :clips, only: [:destroy]
  
  resources :top, only: [:index] do
    collection do
      get 'search'
    end
  end

  root 'top#search'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :brewages
  has_many :clips, dependent: :destroy
  has_many :brands, through: :clips
  has_many :feelings, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :nickname, presence: true

  def remember_me
    true
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up → signup
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :redirect_root, only: :logout
  
  # GET /resource/sign_in
  def newÓ
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  def logout

  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  private

  def redirect_root
    redirect_to root_path unless user_signed_in?
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @clip_brands = current_user.brands.order(updated_at: :DESC)
    # @clip_brands = current_user.brands.order(updated_at: :DESC).page(params[:page]).per(20)
    @user_feelings = Feeling.where(user_id: current_user.id).includes(:brand).order(updated_at: :DESC)
    @feeling_pages = @user_feelings.page(params[:page]).per(20)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_clips.html.haml
.two-column__right-content.clips-index
  %h3 ブックマークした銘柄
  .clips-index__wrapper
    %ul.clips-index__lists.brand-lists
      - if clip_brands.present?
        - clip_brands.each do |brand|
          %li.clips-index__list.brand-list
            = link_to brand_path(brand), target: "blank" do
              .clips-index__list__content.brand-list__content
                .brand-list__content__name
                  - if brand.name_kana.present?
                    %h4 #{brand.name}（#{brand.name_kana}）
                  - else
                    %h4 #{brand.name}
            .clips-index__list__clip.brand-list__content__clip
              - if !Clip.exists?(user_id: current_user.id , brand_id: brand.id)
                = link_to add_brand_path(brand.id), method: :post do
                  %i.far.fa-bookmark
              - else
                = link_to clip_path(brand.id), method: :delete do
                  %i.fas.fa-times-circle
        -# .clips-index__lists__page.brand-lists__page
        -#   = paginate clip_brands
      - else
        %li ブックマークした銘柄はありません

app/views/users/_edit.html.haml
.single-column__form
  %h3 アカウント設定
  = form_for(@user, url: user_registration_path, html: { method: :put }) do |f|
    .field
      = f.label :email, "メールアドレスの編集", class: "form-title"
      = f.email_field :email, autofocus: true, autocomplete: "email", class:"form-text"
    .field
      = f.label :password, "変更後のパスワード（6文字以上）", class: "form-title"
      %small パスワードを変更する場合は以下を入力してください。
      = f.password_field :password, autocomplete: "new-password", class:"form-text"
    .field
      = f.password_field :password_confirmation, autocomplete: "new-password", class:"form-text", placeholder: "確認用"
    .field
      = f.label :current_password, "現在のパスワード", class: "form-title"
      = f.password_field :current_password, autocomplete: "current-password", class:"form-text"
    .actions
      = f.submit "更新する", class: "submit-btn"

app/views/users/_feelings.html.haml
.two-column__right-content.feelings-index
  %h3 きろくした銘柄
  .feelings-index__wrapper
  %ul.feelings-index__lists.brand-lists
    - if user_feelings.present?
      - user_feelings.each do |feeling|
        %li.feelings-index__list.brand-list
          = link_to brand_path(feeling.brand_id), target: "blank" do
            .feelings-index__list__content.brand-list__content
              .brand-list__content__name
                - if feeling.brand.name_kana.present?
                  %h4 #{feeling.brand.name}（#{feeling.brand.name_kana}）
                - else
                  %h4 #{feeling.brand.name}
              .brand-list__content__feeling-rate
                .brand-list__content__feeling-rate-item
                  %a 味わい（辛口 ⇔ 甘口）： 
                  %a #{feeling.flavor}
                .brand-list__content__feeling-rate-item
                  %a 華やかさ： 
                  %a #{feeling.aroma}
                .brand-list__content__feeling-rate-item
                  %a コク： 
                  %a #{feeling.body}
                .brand-list__content__feeling-rate-item
                  %a キレ： 
                  %a #{feeling.sharp}
                .brand-list__content__feeling-rate-item
                  %a お気に入り度： 
                  %a #{feeling.favorite}
                .brand-list__content__feeling-rate-item.updated_at
                  %a 登録日：#{feeling.updated_at}

          .feelings-index__list__clip.brand-list__content__clip
            - if !Clip.exists?(user_id: current_user.id , brand_id: feeling.brand_id)
              = link_to add_brand_path(feeling.brand_id), method: :post do
                %i.far.fa-bookmark
            - else
              = link_to clip_path(feeling.brand_id), method: :delete do
                %i.fas.fa-bookmark
      .feelings-index__lists__page.brand-lists__page
        = paginate @feeling_pages
    - else
      %li きろくした銘柄はありません

app/views/users/show.html.haml
= render "shared/header"
- breadcrumb :mypage, @user
= render partial: 'shared/breadcrumbs'
.container
  .users-show.two-column
    %h2 #{@user.nickname} さんのマイページ
  .users-show.two-column
    .user-show__nav.two-column__left-side.tabs
      -# %label.tab-item{for: "all"} マイページトップ
      %label.tab-item{for: "feelings"} きろくした銘柄
      %label.tab-item{for: "clips"} ブックマークした銘柄
      %label.tab-item{for: "edit"} アカウント設定
      %label.tab-item{for: "logout"} ログアウト
    -# %input#all{type: "radio", name: "tab-item"}
    %input#feelings{type: "radio", name: "tab-item", checked: "checked"}
    %input#clips{type: "radio", name: "tab-item"}
    %input#edit{type: "radio", name: "tab-item"}
    %input#logout{type: "radio", name: "tab-item"}
    .user-show__main__clips.tab-content#all-content.two-column__right-side
      .tab-content__description
        %h3 
    .user-show__main__clips.tab-content#clips-content
      .tab-content__description
        = render partial: "clips", locals: {clip_brands: @clip_brands}
    .user-show__main__feelings.tab-content#feelings-content
      .tab-content__description
        = render partial: "feelings", locals: {user_feelings: @user_feelings}
    .user-show__main__edit.tab-content#edit-content
      .tab-content__description
        = render partial: "edit"
    .user-show__main__logout.tab-content#logout-content
      .tab-content__description
        = link_to logout_path, method: :delete do
          %button.submit-btn.user-show__logout ログアウト
= render 'shared/footer'