config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get     'login',   to: 'users/sessions#new'
    post    'login',   to: 'users/sessions#create'
    delete  'logout',   to: 'users/sessions#destroy'
    get     'signup',  to: 'users/registrations#new'
  end

  resources :users, only: :show

  resources :brands, only: [:index, :show] do
    member do
      post "add", to: "clips#create"
    end
    resources :brewages, only: [:show, :new, :create, :destroy]
    resources :feelings, except: [:index, :show]
  end
  
  resources :clips, only: [:destroy]
  
  resources :top, only: [:index] do
    collection do
      get 'search'
    end
  end

  root 'top#search'
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :brewages
  has_many :clips
  has_many :users, through: :clips
  has_many :feelings

  def self.search(search)
    if search
      Brand.where('name LIKE ?', "%#{search}%")
    else
      puts = "一致するものがありませんでした"
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    @brands = Brand.search(params[:search])
  end

  def show
    @brand = Brand.find(params[:id])
    @brewages = @brand.brewages.where(params[:brand_id])
    @brand_id = Brand.find(params[:id]).id
    @feelings = @brand.feelings.order(created_at: :DESC).where(params[:brand_id])
    if user_signed_in?
      @user = User.find(current_user.id)
      @user_id = current_user.id
      @user_feeling = Feeling.find_by(brand_id: @brand_id, user_id: current_user.id)
    end
  end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/index.html.haml
-# 不要であれば削除
= render "shared/header"
- @brands.each do |brand|
  %ul
    %li
      = link_to brand.name, brand
      = #/{brand.name}

app/views/brands/show.html.haml
= render "shared/header"
- breadcrumb :brand, @brand
= render partial: 'shared/breadcrumbs'
.container
  .brands-show
    .brands-show__content.single-column
      - if @brand.name_kana.present?
        .brands-show__content__name__kana #{@brand.name_kana}
      %h2.brands-show__content__name #{@brand.name}

      .user-btn
        - if current_user
          .brands-show__content__bookmark
            .brands-show__clip
              - if !Clip.exists?(user_id: @current_user , brand_id: @brand_id)
                = link_to add_brand_path(@brand.id), method: :post do
                  ブックマークする
                  %i.far.fa-bookmark
              - else
                = link_to clip_path(@brand.id), class:"marked", method: :delete do
                  ブックマーク済み
                  %i.fas.fa-bookmark

        - if current_user
          .brands-show__content__feeling-btn
            - if !Feeling.exists?(user_id: @current_user , brand_id: @brand_id)
              = link_to new_brand_feeling_path(@brand) do
                きろくをつける
                %i.fas.fa-pen
            - else
              = link_to edit_brand_feeling_path(@brand), class: "marked" do
                きろくを編集する
                %i.fas.fa-pen

      .brands-show__content-top
        .brands-show__content__image
          %ul.slide-image
            - if @brand.brewages.present?
              - @brand.brewages.each do |brewage|
                - if brewage.image.present?
                  %li
                    = image_tag("#{brewage.image}", alt: "#{brewage.name}", class: "image")
            - else
              %li
                = image_tag "/l_e_others_501.png", class: "no-image"

        .brands-show__content__feeling__rate
          - if current_user
            - if !Feeling.exists?(user_id: @current_user , brand_id: @brand_id)
              きろくはありません
            - else
              .brands-show__content__feeling__rate__note
                .rate
                  .rate-name 味わい（辛口 ⇔ 甘口）
                  .rate-border{data: {number: "#{@user_feeling.flavor}"}}
                    %a.rate-border-number{data: {number: "#{@user_feeling.flavor}"}} ▼
                  .rate-name 華やかさ
                  .rate-border{data: {number: "#{@user_feeling.aroma}"}}
                    %a.rate-border-number{data: {number: "#{@user_feeling.aroma}"}} ▼
                  .rate-name コク
                  .rate-border{data: {number: "#{@user_feeling.body}"}}
                    %a.rate-border-number{data: {number: "#{@user_feeling.body}"}} ▼
                  .rate-name キレ
                  .rate-border{data: {number: "#{@user_feeling.sharp}"}}
                    %a.rate-border-number{data: {number: "#{@user_feeling.sharp}"}} ▼
                  -# .rate-name コメント
                  -# .rate-comment #{@user_feeling.comment}
                  .rate-name お気に入り度
                  .rate-border{data: {number: "#{@user_feeling.favorite}"}}
                    %a.rate-border-number{data: {number: "#{@user_feeling.favorite}"}} ▼

      .brands-show__content__brewages
        %h3.brands-show__brewages-title 種類 / 特定名称酒
        .brands-show__brewages-lists
          - if @brand.brewages.present?
            %ul.brands-show__brewages-list
              - @brand.brewages.each do |brewage|
                %li.brands-show__brewages-list-content
                  -# = link_to brand_brewage_path(brewage), class:"link brands-show__brewages-list-name" do
                  %a.link.brands-show__brewages-list-name #{@brand.name} #{brewage.name}
                  %a.brands-show__brewages-list-update.brands-show__brewages-list-name-hover #{@brand.name} #{brewage.name}
                  = image_tag("#{brewage.image}", class: "brands-show__brewages-list-image")
                  - if user_signed_in? && @user_id == brewage.user_id
                    = link_to brand_brewage_path(brewage), method: :delete do
                      %i.fa.fa-trash.trash-ico

              %li.brands-show__brewages-list-content
                .brands-show__brewages-list-content__add
                  = link_to new_brand_brewage_path(@brand), class: "brands-show__brewages-list-add" do
                    %p 種類を追加する
                    .circle
                      %i.fas.fa-plus
          - else
            %p.no-registration 登録されている 種類 / 特定名称酒 はありません 
            %ul.brands-show__brewages-list
              %li.brands-show__brewages-list-content
                .brands-show__brewages-list-content__add
                  = link_to new_brand_brewage_path(@brand), class: "brands-show__brewages-list-add" do
                    %p 種類を追加する
                    .circle
                      %i.fas.fa-plus

      .brands-show__content__feelings
        - if @feelings.present?
          %h3.brands-show__feelings-title みんなのコメント
          .brands-show__feelings-lists
            %ul.brands-show__feelings-list
              - @feelings.each do |feeling|
                -if feeling.comment.present?
                  - if user_signed_in? && @user_id == feeling.user_id
                    %li.brands-show__feelings-list__content.content-mine
                      .brands-show__feelings-list__content-main
                        %a.brands-show__feelings-list__comment
                          #{feeling.comment}
                      .brands-show__feelings-list__content-bottom.bottom-mine
                        %a.brands-show__feelings-list__nickname
                          #{feeling.user.nickname}
                        %a.brands-show__feelings-list__date
                          %span #{feeling.updated_at}
                  - else
                    %li.brands-show__feelings-list__content
                      .brands-show__feelings-list__content-main
                        %a.brands-show__feelings-list__comment
                          #{feeling.comment}
                      .brands-show__feelings-list__content-bottom
                        %a.brands-show__feelings-list__nickname
                          #{feeling.user.nickname}
                        %a.brands-show__feelings-list__date
                          %span #{feeling.updated_at}
        - else
          %h3.brands-show__feelings-title みんなのコメント
          %p.no-registration 登録されているきろくがありません

= render 'shared/footer'
%link{:href => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css", :rel => "stylesheet", :type => "text/css"}/
%link{:href => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css", :rel => "stylesheet", :type => "text/css"}/
%script{:src => "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js", :type => "text/javascript"}